experiment_config:
  model_config:
    n_dim: 512
    n_head: 8
    n_grid_layer: 4
    n_latent_layer: 4
    n_codes: 64
    codebook_size: 1024
    rope_base_height: 10007
    rope_base_width: 5003
    dropout: 0.0
    max_grid_height: 32
    max_grid_width: 32
    n_vocab: 16
    padding_idx: 15
    mask_idx: 14
    pad_weight: 0.1
    gamma: 2.0
    skip_codebook: true
    use_ema: false
    ema_decay: 0.99
    unused_reset_threshold: 0.1
    hot_reset_threshold: 5000
    distance_reset: true
    use_rope: true
    use_ape: true
    return_attn_entropy: false
  beta_commitment: 0.25
  kmeans_init_codebook: false
  kmeans_init_max_datapoints: 2000000
  kmeans_init_batch_size: 100000
  seed: 3014823906
  batch_size: 128
  max_steps: 250000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mask_schedule_type: cosine
  learning_rate: 0.0001
  lr_min: 1.0e-06
  warmup_steps_lr: 100
  decay_steps_lr: 249900
  weight_decay: 0.0
  beta_attn_entropy: 0.0
  mask_pct_start: 0.0
  max_mask_pct: 0.0
  transition_steps_mask_pct: 50000
  warmup_steps_mask_pct: 0
  train_ds: TRAIN
  val_ds: VAL
  limit_training_samples: null
  permute_train: true
  model_src: null

project_config:
  run_name: v1_autoencoder
  project_name: DLR_v4
  checkpoint_dir: runs
  val_check_interval: 1000
  viz_interval: 1000
