experiment_config:
  model_config:
    n_dim: 384
    n_head: 6
    n_grid_layer: 4
    n_latent_layer: 4
    n_codes: 128
    codebook_size: 1024
    rope_base_height: 10007
    rope_base_width: 5003
    dropout: 0.0
    max_grid_height: 32
    max_grid_width: 32
    n_vocab: 16
    padding_idx: 15
    mask_idx: 14
    pad_weight: 0.1
    gamma: 2.0
    skip_codebook: false
    use_ema: true
    ema_decay: 0.95
    unused_reset_threshold: 0.5
    distance_reset: true
    return_attn_entropy: false
  beta_commitment: 0.25
  beta_attn_entropy: 0.0
  kmeans_init_codebook: true
  kmeans_init_max_datapoints: 2000000
  kmeans_init_batch_size: 100000
  batch_size: 64  
  learning_rate: 1.1e-7
  lr_min: 1.1e-9
  seed: 42
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mask_schedule_type: cosine
  warmup_steps_lr: 100
  decay_steps_lr: 999900
  weight_decay: 0.00001
  mask_pct_start: 0.0
  max_mask_pct: 0.0
  transition_steps_mask_pct: 50000
  warmup_steps_mask_pct: 0
  train_ds: TRAIN
  val_ds: VAL
  limit_training_samples: null
  permute_train: true
  model_src: v1.2/best/5495
project_config:
  run_name: v1.2q
  project_name: DLR_v2
  checkpoint_dir: runs
  val_check_interval: 1099
  viz_interval: 1000
