experiment_config: # Removed the initialization from the code, trying by skipping the codebook, VQ/Commitment loss is 0 if skip_codebook is true
  model_config:
    n_dim: 256
    n_head: 4
    n_grid_layer: 4
    n_latent_layer: 4
    n_codes: 128
    codebook_size: 512
    rope_base_height: 10007
    rope_base_width: 5003
    dropout: 0.0
    max_grid_height: 32
    max_grid_width: 32
    n_vocab: 16
    padding_idx: 15
    mask_idx: 14
    pad_weight: 0.1
    gamma: 2.0
    init_mode: normal
    skip_codebook: true
    n_pos: 1024
  seed: 2274030480
  batch_size: 256
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mask_schedule_type: cosine
  learning_rate: 7.0e-06
  lr_min: 1.0e-08
  warmup_steps_lr: 1000
  decay_steps_lr: 990000
  weight_decay: 0.0001
  beta_commitment: 1.0
  mask_pct_start: 0.0
  max_mask_pct: 0.0
  transition_steps_mask_pct: 50000
  warmup_steps_mask_pct: 0
  train_ds: TRAIN
  val_ds: VAL
  limit_training_samples: null
  permute_train: true
  model_src: null
acceleration_config:
  device: auto
  precision: bf16-true
  matmul_precision: high
  compile_model: true
project_config:
  run_name: v3
  project_name: train-vq-vae-v1
  checkpoint_dir: runs
  val_check_interval: 1000
  viz_interval: 1000
