experiment_config:
  model_config:
    n_dim: 256
    n_head: 4
    n_layer_interpreter_exec: 4
    n_layer_interpreter_gen: 4
    n_layer_encoder: 4
    num_iterations: 1

    margin: 0.0
    program_vocab: 2048
    
    # LoRA parameters
    lora_rank: 8
    lora_mlp_layers: 2
    lora_mlp_dim: 256
    grid_height: 32
    grid_width: 32
    latent_height: 8
    latent_width: 8
    conv_block_size: 2
    n_conv_blocks: 2
    n_vocab: 16
    activation: gelu

    encode_norm: true
    decode_norm: true
    dropout: 0.0

  seed: 42
  batch_size: 128
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  learning_rate: 5.0e-04
  lr_min: 5.0e-06
  warmup_steps_lr: 100
  decay_steps_lr: null
  weight_decay: 0.00
  beta_reconstruction: 0.0
  beta_prediction: 1.0
  beta_trajectory: 0.001
  dataset: ALL
  limit_training_samples: null
  limit_validation_samples: 100000
  data_multiplier: 3
  model_src: null
  freeze_autoencoder: false
project_config:
  run_name: v4_dataset
  project_name: prosip-v2
  checkpoint_dir: prosip_runs
  val_check_interval: 1000
  viz_interval: 1000
