experiment_config:
  model_config:
    n_dim: 256
    n_head: 4
    n_grid_layer: 4
    n_latent_layer: 4
    n_codes: 128
    codebook_size: 1024
    rope_base_height: 10007
    rope_base_width: 5003
    dropout: 0.0
    max_grid_height: 32
    max_grid_width: 32
    n_vocab: 16
    padding_idx: 15
    mask_idx: 14
    pad_weight: 0.1
    gamma: 3.0
    skip_codebook: true
    use_ema: false
    ema_decay: 0.99
    unused_reset_threshold: 1.0
    distance_reset: false
  beta_commitment: 0.25
  kmeans_init_codebook: false
  kmeans_init_max_datapoints: 2000000
  batch_size: 128
  learning_rate: 0.0000575
  lr_min: 5.75e-07
  seed: 43
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mask_schedule_type: cosine
  warmup_steps_lr: 100
  decay_steps_lr: 99900
  weight_decay: 0.0001
  mask_pct_start: 0.1
  max_mask_pct: 0.1
  transition_steps_mask_pct: 50000
  warmup_steps_mask_pct: 0
  train_ds: TRAIN
  val_ds: VAL
  limit_training_samples: null
  permute_train: true
  model_src: null
project_config:
  run_name: dlr_v3_noise_01
  project_name: DLR_v1
  checkpoint_dir: runs
  val_check_interval: 1099
  viz_interval: 1000
