defaults:
  - _self_
  - model: default
  - optimizer: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Basic configuration
project_name: pips
seed: 42
debug: false

# Data configuration
data:
  input_size: 30
  batch_size: 32 