experiment_config:
  model_config:
    n_vocab: 16
    n_dim: 256
    n_codes: 64
    n_layers: 2
    n_heads: 4
    n_conv_blocks: 2
    conv_block_size: 2
    codebook_size: 0
    grid_height: 32
    grid_width: 32
    encode_norm: true
    use_ema: true
    decay: 0.99
    distance_reset: true
    unused_reset_threshold: 1.0
    hot_reset_threshold: 500
    pad_weight: 1.0
    gamma: 2.0
  seed: 3186270169
  batch_size: 4
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mask_schedule_type: cosine
  learning_rate: 0.0001
  lr_min: 1.0e-06
  warmup_steps_lr: 10000
  decay_steps_lr: 990000
  weight_decay: 0.0001
  beta_commitment: 0.25
  mask_pct_start: 0.0
  max_mask_pct: 0.0
  transition_steps_mask_pct: 50000
  warmup_steps_mask_pct: 0
  train_ds: TRAIN
  val_ds: VAL
  limit_training_samples: null
  permute_train: true
  model_src: null
  kmeans_init_codebook: false
  kmeans_init_max_datapoints: 500000
  kmeans_init_batch_size: 100000
project_config:
  run_name: proud-seal-616-v5
  project_name: CTD_v1
  checkpoint_dir: runs
  val_check_interval: 1000
  viz_interval: 1000
