experiment_config:
  model_config:
    n_dim: 256
    n_head: 4
    activation: gelu
    n_vocab: 16
    n_layer_encoder: 1
    n_layer_interpreter_exec: 1
    n_layer_interpreter_gen: 1
    dropout: 0.0
    program_vocab: 2048
    num_iterations: 1
    latent_height: 8
    latent_width: 8
    conv_block_size: 2
    n_conv_blocks: 2
    grid_height: 32
    grid_width: 32
    encode_norm: true
    decode_norm: true
    margin: 0.0
    rope_base: 4000
    rank: 8
    mlp_layers: 1
    mlp_dim: 256
  seed: 3062342864
  batch_size: 8
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  learning_rate: 0.0001
  lr_min: 1.0e-06
  warmup_steps_lr: 1000
  decay_steps_lr: 999000
  em_start_epoch: 0
  m_step_lr_multiplier: 10
  adamw_betas_1: 0.9
  adamw_betas_2: 0.999
  weight_decay: 0.0001
  beta_reconstruction: 1.0
  beta_prediction: 1.0
  beta_trajectory: 1.0
  dataset: ALL
  group_by_program: true
  limit_training_samples: null
  limit_validation_samples: null
  data_multiplier: 2
  model_src: null
  train_only_program_embeddings: false
  freeze_autoencoder: false
project_config:
  run_name: swift-robin-276
  project_name: prosip-test
  checkpoint_dir: prosip_runs
  val_check_interval: 1000
  viz_interval: 1000
