experiment_config:
  model_config:
    n_dim: 256
    n_head: 4
    n_layer_interpreter_exec: 2
    n_layer_interpreter_gen: 2
    num_iterations: 1

    margin: 0.1
    program_vocab: 2048
    # LoRA parameters
    lora_rank: 4
    lora_mlp_layers: 2
    lora_mlp_dim: 256
    grid_height: 32
    grid_width: 32
    latent_height: 5
    latent_width: 5
    conv_block_size: 2
    n_conv_blocks: 2
    n_layer_encoder: 4
    n_vocab: 16
    activation: gelu

    encode_norm: true
    decode_norm: true
    dropout: 0.0

  seed: 1004573656
  batch_size: 64
  max_steps: 1000000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  learning_rate: 0.001
  lr_min: 1.0e-05
  warmup_steps_lr: 10000
  decay_steps_lr: null
  weight_decay: 0.00
  beta_reconstruction: 1.0
  beta_prediction: 1.0
  beta_trajectory: 0.1
  dataset: ALL
  limit_training_samples: null
  limit_validation_samples: 2048
  data_multiplier: 2
  model_src: null
  freeze_autoencoder: true
project_config:
  run_name: fair-eagle-dataset
  project_name: prosip-v1
  checkpoint_dir: prosip_runs
  val_check_interval: 1000
  viz_interval: 1000
